import turtle
turtle.begin_poly()
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.goto(50,-130)
turtle.goto(0,-100)
turtle.home()
turtle.end_fill()
turtle.end_poly()
shape = turtle.get_poly()
turtle.register_shape("shape",shape)
turtle.shape("shape")
turtle.mainloop()